In [2]:
from data_preparation import load_all_data
from riskm_config import RMC

In [1]:
%%time
df = spark.read.csv(path=os.path.join(RMC.OUTPUT_DIR, RMC.PROPHET_INPUT_ALL_RESHAPED + '.csv'), 
                    header=True, inferSchema=True)

NameError: name 'RMC' is not defined

In [13]:
%%time
df.count(), len(df.columns)

CPU times: user 4 ms, sys: 4 ms, total: 8 ms
Wall time: 21.1 s


(7210721, 80)

In [3]:
%%time
x, y, _,_,_,_, _, _, _ = load_all_data(True, False, False, True)

2018-04-25 12:49:53,908 - RiskM - INFO - Loading training data ...
2018-04-25 12:49:55,643 - RiskM - INFO - Loading training data done.


CPU times: user 0 ns, sys: 1.74 s, total: 1.74 s
Wall time: 1.74 s


In [4]:
x.shape, y.shape

((10000, 721, 78), (10000, 40))

In [5]:
y[0, 0].__class__


numpy.float64

In [6]:
x_t, y_t, i_t, x_v, y_v, i_v, _, _, _ = load_all_data(True, True, False, False)

2018-04-25 12:50:06,512 - RiskM - INFO - Loading training data ...
2018-04-25 12:50:06,546 - RiskM - INFO - Loading training data done.
2018-04-25 12:50:06,547 - RiskM - INFO - Loading prepared validation data ...
2018-04-25 12:50:06,551 - RiskM - INFO - Loading prepared validation data done.


In [19]:
x_t.shape, y_t.shape, i_t.shape, x_v.shape, y_v.shape, i_v.shape

((9500, 13, 78), (9500,), (9500,), (500, 13, 78), (500,), (500,))

In [18]:
i_v[0]

4813

In [8]:
df.where((df.SCENARIO==int(i_v[0]+1)) & (df.MONTH==201812)).show()

NameError: name 'df' is not defined

In [9]:
x[i_v[0]][12]

array([-0.6789  , -2.354866,  3.5042  ,  2.037487,  0.5     ,  5.      ,
        0.      ,  0.      , -0.6789  , -0.5848  ,  1.069737,  1.192074,
        1.300469,  1.393082,  1.468285,  1.527001,  1.575731,  1.620287,
        1.664694,  1.711749, -0.397427,  1.762674,  1.815953,  1.869907,
        1.923324,  1.975433,  2.025804,  2.07404 ,  2.119984,  2.163562,
        2.204777, -0.189985,  2.243639,  0.025067,  0.218714,  0.413713,
        0.599265,  0.773937,  0.931455,  1.024233,  0.139029,  0.      ,
        0.      ,  4.89784 ,  4.1293  ,  1.005619,  0.994412, -0.6789  ,
       -0.5848  ,  1.1009  ,  1.2317  ,  1.3488  ,  1.4497  ,  1.532   ,
        1.5962  ,  1.6495  ,  1.6986  ,  1.7483  ,  1.8021  , -0.3978  ,
        1.8617  ,  1.9254  ,  1.9912  ,  2.0576  ,  2.1236  ,  2.1886  ,
        2.252   ,  2.3135  ,  2.3729  ,  2.4301  , -0.1905  ,  2.485   ,
        0.0252  ,  0.2205  ,  0.4186  ,  0.6088  ,  0.7897  ,  0.9546  ])

In [10]:
x_v[0][12]

array([-0.6789  , -2.354866,  3.5042  ,  2.037487,  0.5     ,  5.      ,
        0.      ,  0.      , -0.6789  , -0.5848  ,  1.069737,  1.192074,
        1.300469,  1.393082,  1.468285,  1.527001,  1.575731,  1.620287,
        1.664694,  1.711749, -0.397427,  1.762674,  1.815953,  1.869907,
        1.923324,  1.975433,  2.025804,  2.07404 ,  2.119984,  2.163562,
        2.204777, -0.189985,  2.243639,  0.025067,  0.218714,  0.413713,
        0.599265,  0.773937,  0.931455,  1.024233,  0.139029,  0.      ,
        0.      ,  4.89784 ,  4.1293  ,  1.005619,  0.994412, -0.6789  ,
       -0.5848  ,  1.1009  ,  1.2317  ,  1.3488  ,  1.4497  ,  1.532   ,
        1.5962  ,  1.6495  ,  1.6986  ,  1.7483  ,  1.8021  , -0.3978  ,
        1.8617  ,  1.9254  ,  1.9912  ,  2.0576  ,  2.1236  ,  2.1886  ,
        2.252   ,  2.3135  ,  2.3729  ,  2.4301  , -0.1905  ,  2.485   ,
        0.0252  ,  0.2205  ,  0.4186  ,  0.6088  ,  0.7897  ,  0.9546  ])

In [11]:
y[i_v[0]]

array([  8.46492756e+08,   1.05475539e+09,   1.23087349e+09,
         1.43701171e+09,   1.65119659e+09,   1.89049955e+09,
         2.12333765e+09,   2.29504945e+09,   2.29417317e+09,
         2.28783764e+09,   2.28488868e+09,   2.28768343e+09,
         2.29358779e+09,   2.30208364e+09,   2.30989350e+09,
         2.28181994e+09,   2.25019146e+09,   2.24999260e+09,
         2.23731632e+09,   2.23216676e+09,   2.21919788e+09,
         2.19885891e+09,   2.17501560e+09,   2.15530217e+09,
         2.13897933e+09,   2.12471249e+09,   2.11391128e+09,
         2.10336085e+09,   2.09126314e+09,   2.08451496e+09,
         2.07719250e+09,   2.07358488e+09,   2.07201554e+09,
         2.07377738e+09,   2.07519372e+09,   2.07660109e+09,
         2.07437669e+09,   2.07144520e+09,   2.06809746e+09,
         2.06360812e+09])

In [12]:
%%time
df = spark.read.csv(path=os.path.join(RMC.OUTPUT_DIR, RMC.PROPHET_OUTPUT_ALL_PROPER + '.csv'), 
                    header=True, inferSchema=True, sep=';')

CPU times: user 0 ns, sys: 4 ms, total: 4 ms
Wall time: 3.53 s


In [19]:
df.where((df.SCENARIO==int(i_v[0]))).show()

+--------+--------------+---------------+--------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+--------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+
|SCENARIO|OWN_FUNDS_2018| OWN_FUNDS_2019|OWN_FUNDS_2020| OWN_FUNDS_2021| OWN_FUNDS_2022| OWN_FUNDS_2023| OWN_FUNDS_2024| OWN_FUNDS_2025| OWN_FUNDS_2026| OWN_FUNDS_2027| OWN_FUNDS_2028| OWN_FUNDS_2029| OWN_FUNDS_2030| OWN_FUNDS_2031| OWN_FUNDS_2032| OWN_FUNDS_2033| OWN_FUNDS_2034| OWN_FUNDS_2035| OWN_FUNDS_2036| OWN_FUNDS_2037| OWN_FUNDS_2038| OWN_FUN

In [21]:
i_v

array([4813, 2530, 7694, 4267, 6820, 4225, 1127, 1054, 3748, 6152, 3240,
       2430, 3144, 7150, 4529, 4189, 6413, 5796, 1381, 6418,  584, 6918,
        236, 8924, 2926, 2634,  246, 2280, 3581,  383, 6352, 1744, 2616,
       2626, 6455, 6021,  969, 3480, 3512, 5683, 9750, 9031, 9207, 9790,
       7100, 1841, 8713, 2035, 1066, 2200, 5802, 5210,    3, 2939, 6802,
       3341, 8062, 1584, 7352, 5696, 1871, 9892, 4453, 2009, 9527, 3741,
       9099, 8202, 1481, 8229, 7597, 8209, 7496, 6054, 7899, 3201,  358,
        746, 2840,  623, 8568, 2645, 2496,  120, 3977, 3202, 5972, 8226,
       7870, 6690, 3836,  277, 1280, 8406, 5508, 5407, 9241, 9341,  750,
       8339, 9523, 3675, 7911, 6485, 6263, 3778, 1747, 3788,   49, 6786,
       1086, 6948, 4894,  816, 8942, 1556, 6692, 7326,  686, 8100, 9749,
       9921, 7466, 6084, 1331, 9156, 7752, 8524, 6957,  318, 3937,  802,
       4176, 5493, 2744, 1823, 6647, 3968, 1686, 2521, 9864, 8784, 8907,
       2642, 6673, 4480, 9378, 9488, 1243, 5866,  2

In [22]:
i_v[i_v > 2051] += 1

In [23]:
i_v

array([4814, 2531, 7695, 4268, 6821, 4226, 1127, 1054, 3749, 6153, 3241,
       2431, 3145, 7151, 4530, 4190, 6414, 5797, 1381, 6419,  584, 6919,
        236, 8925, 2927, 2635,  246, 2281, 3582,  383, 6353, 1744, 2617,
       2627, 6456, 6022,  969, 3481, 3513, 5684, 9751, 9032, 9208, 9791,
       7101, 1841, 8714, 2035, 1066, 2201, 5803, 5211,    3, 2940, 6803,
       3342, 8063, 1584, 7353, 5697, 1871, 9893, 4454, 2009, 9528, 3742,
       9100, 8203, 1481, 8230, 7598, 8210, 7497, 6055, 7900, 3202,  358,
        746, 2841,  623, 8569, 2646, 2497,  120, 3978, 3203, 5973, 8227,
       7871, 6691, 3837,  277, 1280, 8407, 5509, 5408, 9242, 9342,  750,
       8340, 9524, 3676, 7912, 6486, 6264, 3779, 1747, 3789,   49, 6787,
       1086, 6949, 4895,  816, 8943, 1556, 6693, 7327,  686, 8101, 9750,
       9922, 7467, 6085, 1331, 9157, 7753, 8525, 6958,  318, 3938,  802,
       4177, 5494, 2745, 1823, 6648, 3969, 1686, 2522, 9865, 8785, 8908,
       2643, 6674, 4481, 9379, 9489, 1243, 5867,  2